#!/bin/bash

if [ ! -d "venv" ];
then
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    deactivate
fi

source venv/bin/activate

if [ $# -eq 1 ];
then
    python main.py < $1
else
    python main.py
fi

deactivate